### ISSUE TITLE
Errors in Jupyter

### ISSUE THREAD

**Issue by opardal** [Oliph/likertScalePlot#1]
Hey Oliph,

I have used your code to draw some graphs, so, first of all, thanks a lot. I searched several codes here in Github related to Likert scale and your code made sense for me. I am a beginner in Python and in GitHub, so be skeptical with this message. When I ran your code in Jupyter I got some errors. The first one was related to the compute_middle_sum function. Then I changed the exception from ValueError to KeyError and it worked well. The other problem I found was in percentages indexes in add_labels function. I made some changes and everything worked well. I would like to hear you about those errors and check if I made the proper changes. Thank you again!

**Comment by jeffbl** [comment]
Yes, thanks for making this available!
When I try and run the code in Jupyter I also get a "KeyError: None" , but when I make the same change in line 95 to KeyError rather than ValueError, I also at least get a plot, although I also get an "IndexError: too many indices for array". Trace here:

IndexError                                Traceback (most recent call last)
<ipython-input-3-a25aa7cdd9d6> in <module>
    303 
    304 if __name__ == "__main__":
--> 305     main()
    306 

<ipython-input-3-a25aa7cdd9d6> in main()
    299                          columns=["SD", "D", "N", "A", "SA", 'TEST'],
    300                          index=["Key 1", "Key B", "Key III"])
--> 301     likert_scale(dummy)
    302 
    303 

<ipython-input-3-a25aa7cdd9d6> in likert_scale(df, normalise, labels, middle_line, legend, rotation)
    259     # Add labels to each box
    260     if labels:
--> 261         add_labels(df, ax, bars, rotation)
    262 
    263     # Create a line on the middle

<ipython-input-3-a25aa7cdd9d6> in add_labels(df, ax, bars, rotation)
    168             x = 0.5 *bar.get_width() +bl[0]
    169             y = 0.5 *bar.get_height() +bl[1]
--> 170             ax.text(x, y, "{}".format(percentages[i, j]), ha='center', rotation=rotation)
    171 
    172 

IndexError: too many indices for array

**Comment by opardal** [comment]
@jeffbl , you should change the line 170 to:
ax.text(x, y, "{}".format(percentages[i][j]), ha='center', rotation=rotation)

Try this and let me know it it worked!

**Comment by Oliph** [comment]
Hi, 
First, sorry for the late reply, I was away. 
Second, I am happy to see that my code is used by others. I updated the code from my personal last version. It should include the fix for the index error. 
If you have any other issue, I will be happy to fix it (as well as any suggestion). I  close this issue as it should be fixed, if not I will reopen it.
